---

stages:
  - test
  - build

include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'

  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'

  - project: 'saltbox/ci-lib'
    file: 'check-addon-image-tags.yml'

  - project: 'saltbox/ci-lib'
    file: 'mirror-repo.yml'


.build-grafana-image:
  extends: .build-image
  variables:
    DOCKERFILE: './grafana/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/grafana'


.build-grafana-loki-image:
  extends: .build-image
  variables:
    DOCKERFILE: './grafana_loki/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/grafana-loki'


.build-prometheus-image:
  extends: .build-image
  variables:
    DOCKERFILE: './prometheus/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/prometheus'


.build-promtail-image:
  extends: .build-image
  variables:
    DOCKERFILE: './promtail/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/promtail'


.build-cadvisor-image:
  extends: .build-image
  variables:
    DOCKERFILE: './cadvisor/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/cadvisor'


.build-node-exporter-image:
  extends: .build-image
  variables:
    DOCKERFILE: './node_exporter/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/node-exporter'


.build-mongo-exporter-image:
  extends: .build-image
  variables:
    DOCKERFILE: './mongo_exporter/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/mongo-exporter'


Build Grafana image:
  extends: .build-grafana-image


Build Prometheus image:
  extends: .build-prometheus-image


Build Promtail image:
  extends: .build-promtail-image


Build Grafana Loki image:
  extends: .build-grafana-loki-image


Build cAdvisor image:
  extends: .build-cadvisor-image


Build Node Exporter:
  extends: .build-node-exporter-image


Build Mongo Exporter image:
  extends: .build-mongo-exporter-image


Mirror Repository:
  extends: .mirror-repo
  stage: build
