include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        when: never
      - when: always


.build-grafana-image:
  extends: .build-image
  variables:
    DOCKERFILE: './grafana/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/grafana'


.build-grafana-loki-image:
  extends: .build-image
  variables:
    DOCKERFILE: './grafana_loki/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/grafana-loki'


.build-prometheus-image:
  extends: .build-image
  variables:
    DOCKERFILE: './prometheus/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/prometheus'


.build-promtail-image:
  extends: .build-image
  variables:
    DOCKERFILE: './promtail/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/promtail'


.build-cadvisor-image:
  extends: .build-image
  variables:
    DOCKERFILE: './cadvisor/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/cadvisor'


Build Grafana image for tag:
  extends: .build-grafana-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Grafana image for branch:
  extends: .build-grafana-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build Prometheus image for tag:
  extends: .build-prometheus-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Prometheus image for branch:
  extends: .build-prometheus-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build Promtail image for tag:
  extends: .build-promtail-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Promtail image for branch:
  extends: .build-promtail-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build Grafana Loki image for tag:
  extends: .build-grafana-loki-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Grafana Loki image for branch:
  extends: .build-grafana-loki-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build cAdvisor image for tag:
  extends: .build-cadvisor-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build cAdvisor image for branch:
  extends: .build-cadvisor-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH'
