include:
  # Requires standard stage `test`
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'


stages:
  - build


.default:
  extends: .build-image
  dependencies: []


.build-grafana-image:
  extends: .default
  stage: build
  variables:
    DOCKERFILE: './grafana/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/grafana'


.build-grafana-loki-image:
  extends: .default
  stage: build
  variables:
    DOCKERFILE: './grafana_loki/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/grafana-loki'


.build-prometheus-image:
  extends: .default
  stage: build
  variables:
    DOCKERFILE: './grafana/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/prometheus'


.build-promtail-image:
  extends: .default
  stage: build
  variables:
    DOCKERFILE: './promtail/Dockerfile'
    REGISTRY_ADDITIONAL_PATH: '/promtail'


Build Grafana image for tag:
  extends: .build-grafana-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Grafana image for branch:
  extends: .build-grafana-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build Prometheus image for tag:
  extends: .build-prometheus-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Prometheus image for branch:
  extends: .build-prometheus-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build Promtail image for tag:
  extends: .build-promtail-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Promtail image for branch:
  extends: .build-promtail-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Build Grafana Loki image for tag:
  extends: .build-grafana-loki-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Grafana Loki image for branch:
  extends: .build-grafana-loki-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_REF_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH'
