x-default-service: &default
  restart: 'always'
  stop_grace_period: ${STOP_GRACE_PERIOD}


services:
  saltbox-metric: &metric
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-metric-backend:${METRIC_IMAGE_TAG}'
    command: 'uvicorn'
    environment:
      LOG_LEVEL: '${METRIC_LOG_LEVEL:-info}'
      BASE_URL_ROOT_PATH: '${METRIC_BACKEND_PATH}'
      TIMEOUT_GRACEFUL_SHUTDOWN: '${BACKEND_SHUTDOWN_TIMEOUT_SEC}'
      BASIC_AUTH_USERNAME: '${BASIC_AUTH_USERNAME:-}'
      BASIC_AUTH_PASSWORD: '${BASIC_AUTH_PASSWORD:-}'
      REDIS_CA_CERT: '/etc/redis/certs/ca.crt'
      REDIS_URL: 'rediss://redis-salt:6379/2'
      REDIS_USERNAME: '${REDIS_SALT_USERNAME}'
      KEYCLOAK_FRONT_URL: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}'
      KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
      KEYCLOAK_CLIENT: '${KEYCLOAK_CLIENT}'
      #NOTE: Gateway environment variables
      DISCOVERY_SERVER_SCHEME: 'https'
      DISCOVERY_SERVER_WS_SCHEME: 'wss'
      DISCOVERY_SERVER_OUTER_SOCKET: '${WEB_SERVER_OUTER_SOCKET}'
      DISCOVERY_DISCOVERY_URL: 'http://saltbox-gateway:${GATEWAY_HTTP_PORT}/api/discovery'
      DISCOVERY_SERVICE_NAME: '${METRIC_SERVICE_NAME}'
      DISCOVERY_SERVICE_TITLE: '${METRIC_SERVICE_TITLE}'
      DISCOVERY_SERVICE_DESCRIPTION: '${METRIC_SERVICE_DESCRIPTION}'
      DISCOVERY_SERVICE_VENDOR: '${METRIC_SERVICE_VENDOR}'
      DISCOVERY_SERVICE_TYPE: '${METRIC_SERVICE_TYPE}'
      DISCOVERY_INSTANCE_ID: '${METRIC_INSTANCE_ID}'
      DISCOVERY_INSTANCE_HOST: '${METRIC_HOST}'
      DISCOVERY_INSTANCE_PORT: '${METRIC_PORT:-8000}'
      DISCOVERY_FRONT_CONTAINER_NAME: '${METRIC_FRONT_CONTAINER_NAME:-saltbox-metric-front}'
      DISCOVERY_FRONT_CONTAINER_PORT: '${METRIC_FRONT_CONTAINER_PORT:-3000}'
    volumes:
      - type: volume
        source: redis_salt_certs
        target: '/etc/redis/certs/'
        read_only: true
      - 'saltbox_metric_var:/var/lib/saltbox-metric/'
    secrets:
      - redis_taskiq_password
      - redis_salt_password
      - keycloak_client_saltbox_core_password
    expose:
      - '${CORE_PORT}'  #FIXME: Inentory looks to have own backend port variable
    depends_on:
      redis-taskiq:
        condition: service_started
        restart: false
      rabbitmq:
        condition: service_healthy
        restart: false

  saltbox-metric-app:
    <<: *metric
    command: 'shell saltbox-metric-app'
    expose: [ ]

  saltbox-metric-frontend:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-frontend-metric:${FRONTEND_IMAGE_TAG}'
    expose:
      - ${FRONTEND_HTTP_PORT}

  proxy:
    volumes:
      - '${METRIC_OUTER_PATH}/nginx_include.conf:${WEB_SERVER_SALTBOX_INCLUDES_DIR}/10-metrics.conf:ro'

  keycloak-init:
    environment:
      KEYCLOAK_CLIENT_GRAFANA: '${KEYCLOAK_CLIENT_GRAFANA}'
    secrets:
      - keycloak_client_grafana_password

  grafana:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-metric-compose/grafana:${GRAFANA_IMAGE_TAG}'
    environment:
      GF_SERVER_PROTOCOL: 'http'
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SERVER_DOMAIN: '${WEB_SERVER_OUTER_SOCKET}'
      GF_SERVER_ROOT_URL: 'https://${WEB_SERVER_OUTER_SOCKET}/grafana/'
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_AUTH_BASIC_ENABLED: false
      GF_AUTH_DISABLE_LOGIN_FORM:  true
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: true
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: true
      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: true
      GF_AUTH_GENERIC_OAUTH_USE_TOKEN_INFO_ENDPOINT: false
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: '${KEYCLOAK_CLIENT_GRAFANA}'
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: 'full_name'
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: 'username'
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: 'email'
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE: '/run/secrets/keycloak_client_grafana_password'
      GF_AUTH_GENERIC_OAUTH_SCOPES: 'openid email profile offline_access roles'
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth'
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token'
      GF_AUTH_GENERIC_OAUTH_API_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo'
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(resource_access.grafana.roles, 'grafana_admin') && 'Admin' || 'Viewer'"
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: '${SMTP_HOST}'
      GF_SMTP_USER: '${SMTP_USER}'
      GF_SMTP_FROM_ADDRESS: '${SMTP_FROM_ADDRESS}'
      GF_SMTP_ALERT_EMAILS: '${SMTP_ALERT_EMAILS}'
      GF_SMTP_FROM_NAME: 'Salt.Box Alerts'
      GF_SMTP_SKIP_VERIFY: false
      GF_LOG_LEVEL: '${METRIC_LOG_LEVEL:-info}'
    secrets:
      - keycloak_client_grafana_password
      - grafana_smtp_password
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_var:/var/lib/grafana'
    depends_on:
      grafana-loki:
        condition: service_healthy
      promtail:
        condition: service_started
      prometheus:
        condition: service_started

  grafana-loki:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-metric-compose/grafana-loki:${GRAFANA_IMAGE_TAG}'
    expose:
      - '3100'
    volumes:
      - 'grafana_loki_data:/data/grafana_loki'

  promtail:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-metric-compose/promtail:${METRIC_OBSERVABILITY_IMAGE_TAG}'
    expose:
      - '9080'
    volumes:
      - 'promtail_data:/data/promtail'
      - '${METRIC_DOCKER_SOCKET}:/var/run/docker.sock'
      - '${METRIC_DOCKER_CONTAINERS_PATH}:/var/lib/docker/containers:ro'

  prometheus:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-metric-compose/prometheus:${METRIC_OBSERVABILITY_IMAGE_TAG}'
    environment:
      WEB_SERVER_OUTER_SOCKET: "${WEB_SERVER_OUTER_SOCKET}"
    extra_hosts:
      - "host.saltbox:host-gateway"
    ports:
      - '9090:9090'
    volumes:
      - 'prometheus_data:/data/prometheus'

  cadvisor:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-metric-compose/cadvisor:${METRIC_OBSERVABILITY_IMAGE_TAG}'
    expose:
      - '8080'
    volumes:
      - /:/rootfs:ro
      - '${METRIC_SYSFS_PATH}:/sys:ro'
      - '${METRIC_DOCKER_SOCKET}:/var/run/docker.sock'
      - '${METRIC_DOCKER_CONTAINERS_PATH}:/var/lib/docker/containers:ro'
      - '${METRIC_CONTAINERD_SOCKET}:/run/containerd/containerd.sock'
    depends_on:
      prometheus:
        condition: service_started

  node-exporter:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-metric-compose/node-exporter:${METRIC_OBSERVABILITY_IMAGE_TAG}'
    command:
      - '--path.rootfs=/host'
    expose:
      - '9100'
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'

  mongo-exporter:
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-metric-compose/mongo-exporter:${METRIC_OBSERVABILITY_IMAGE_TAG}'
    environment:
      MONGO_USER: '${MONGO_EXPORTER}'
      MONGO_HOSTNAME: '${MONGO_HOSTNAME}'
      MONGO_AUDIT_HOSTNAME: '${MONGO_AUDIT_HOSTNAME}'
      MONGO_REPLICA_SET: '${MONGO_REPLICA_SET}'
      MONGO_AUDIT_REPLICA_SET: '${MONGO_AUDIT_REPLICA_SET}'
    expose:
      - '9216'
    secrets:
      - mongo_exporter_password
    depends_on:
      mongo:
        condition: service_healthy
        restart: false

volumes:
  saltbox_metric_var: {}
  grafana_var: {}
  grafana_loki_data: {}
  promtail_data: {}
  prometheus_data: {}

secrets:
  keycloak_client_grafana_password:
    file: secrets/keycloak_client_grafana_password
  grafana_smtp_password:
    file: secrets/grafana_smtp_password
