services:
  grafana:
    build:
      context: "${METRIC_OUTER_PATH}"
      dockerfile: ./grafana/Dockerfile

  grafana-loki:
    build:
      context: "${METRIC_OUTER_PATH}"
      dockerfile: ./grafana_loki/Dockerfile

  prometheus:
    build:
      context: "${METRIC_OUTER_PATH}"
      dockerfile: ./prometheus/Dockerfile

  promtail:
    build:
      context: "${METRIC_OUTER_PATH}"
      dockerfile: ./promtail/Dockerfile

  cadvisor:
    build:
      context: "${METRIC_OUTER_PATH}"
      dockerfile: ./cadvisor/Dockerfile

  node-exporter:
    build:
      context: "${METRIC_OUTER_PATH}"
      dockerfile: ./node_exporter/Dockerfile

  mongo-exporter:
    build:
      context: "${METRIC_OUTER_PATH}"
      dockerfile: ./mongo_exporter/Dockerfile
