---

## Salt.Box Compose metric override file for dev-mode.

x-metric-watch: &metric-watch
  - action: sync+restart
    path: '${METRIC_BUILD_DIR}'
    target: /mnt/saltbox-metric
    ignore:
      - saltbox_metric/__pycache__/
      - '**/*.pyc'
      - '**/*.egg-info/'
  - action: rebuild
    path: '${METRIC_BUILD_DIR}/requirements.txt'
  - action: rebuild
    path: '${METRIC_BUILD_DIR}/local_requirements.txt'

services:
  saltbox-metric: &metric
    build:
      context: '${METRIC_BUILD_DIR}'
      target: dev
    environment:
      - LOG_LEVEL=DEBUG
      - DISCOVERY_LOG_LEVEL=DEBUG
    tty: true  # colorize logs
    image: 'saltbox-metric:dev'
    volumes:
      - '${METRIC_BUILD_DIR}:/mnt/saltbox-metric'
      - '${SDK_DIR}:/mnt/saltbox-sdk'
    tmpfs:
      - '/mnt/saltbox-sdk/build/'
      - '/mnt/saltbox-sdk/saltbox_sdk.egg-info/'
    develop:
      watch: *metric-watch

  saltbox-metric-app:
    <<: *metric
    develop:
      watch: *metric-watch
