x-default-service: &default
  restart: 'on-failure'
  stop_grace_period: ${STOP_GRACE_PERIOD}

services:
  saltbox-metric: &metric
    <<: *default
    image: '${IMAGE_REGISTRY}/saltbox-metric-backend:${METRIC_IMAGE_TAG}'
    command: 'uvicorn'
    environment:
      LOG_LEVEL: '${METRIC_LOG_LEVEL:-info}'
      BASE_URL_ROOT_PATH: '${METRIC_BACKEND_PATH}'
      TIMEOUT_GRACEFUL_SHUTDOWN: '${BACKEND_SHUTDOWN_TIMEOUT_SEC}'
      BASIC_AUTH_USERNAME: '${BASIC_AUTH_USERNAME:-}'
      BASIC_AUTH_PASSWORD: '${BASIC_AUTH_PASSWORD:-}'
      REDIS_CA_CERT: '/etc/redis/certs/ca.crt'
      REDIS_URL: 'rediss://redis-salt:6379/2'
      REDIS_USERNAME: '${REDIS_SALT_USERNAME}'
      KEYCLOAK_FRONT_URL: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}'
      KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
      KEYCLOAK_CLIENT: '${KEYCLOAK_CLIENT}'
      # Gateway environment variables
      DISCOVERY_SERVER_SCHEME: 'https'
      DISCOVERY_SERVER_WS_SCHEME: 'wss'
      DISCOVERY_SERVER_OUTER_SOCKET: '${WEB_SERVER_OUTER_SOCKET}'
      DISCOVERY_DISCOVERY_URL: 'http://saltbox-gateway:${GATEWAY_HTTP_PORT}/api/discovery'
      DISCOVERY_SERVICE_NAME: '${METRIC_SERVICE_NAME}'
      DISCOVERY_SERVICE_TITLE: '${METRIC_SERVICE_TITLE}'
      DISCOVERY_SERVICE_DESCRIPTION: '${METRIC_SERVICE_DESCRIPTION}'
      DISCOVERY_SERVICE_VENDOR: '${METRIC_SERVICE_VENDOR}'
      DISCOVERY_SERVICE_TYPE: '${METRIC_SERVICE_TYPE}'
      DISCOVERY_INSTANCE_ID: '${METRIC_INSTANCE_ID}'
      DISCOVERY_INSTANCE_HOST: '${METRIC_HOST}'
      DISCOVERY_INSTANCE_PORT: '${METRIC_PORT:-8000}'
      DISCOVERY_FRONT_CONTAINER_NAME: '${METRIC_FRONT_CONTAINER_NAME:-saltbox-metric-front}'
      DISCOVERY_FRONT_CONTAINER_PORT: '${METRIC_FRONT_CONTAINER_PORT:-3000}'
    volumes:
      - type: volume
        source: redis_salt_certs
        target: '/etc/redis/certs/'
        read_only: true
      - 'saltbox_metric_var:/var/lib/saltbox-metric/'
    secrets:
      - redis_taskiq_password
      - redis_salt_password
      - keycloak_client_saltbox_core_password
    expose:
      - '${CORE_PORT}'  # FIXME Inentory looks to have own backend port variable
    depends_on:
      redis-taskiq:
        condition: service_started
        restart: false
      rabbitmq:
        condition: service_healthy
        restart: false

  saltbox-metric-app:
    <<: *metric
    command: 'shell saltbox-metric-app'
    expose: [ ]

#  saltbox-metric-frontend:
#    <<: *default
#    image: '${IMAGE_REGISTRY}/saltbox-metric-frontend:${FRONTEND_IMAGE_TAG}'
#    expose:
#      - ${FRONTEND_HTTP_PORT}

  proxy:
    volumes:
      - ./proxy/includes/metrics.enabled.conf:/etc/nginx/includes/10-metrics.conf:ro

  keycloak-init:
    environment:
      KEYCLOAK_CLIENT_GRAFANA: '${KEYCLOAK_CLIENT_GRAFANA}'
    secrets:
      - keycloak_client_grafana_password

  grafana:
    <<: *default
    build: 
      context: '${METRIC_OUTER_PATH}'
    environment:
      GF_SERVER_PROTOCOL: 'http'
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SERVER_DOMAIN: '${WEB_SERVER_OUTER_SOCKET}'
      GF_SERVER_ROOT_URL: 'https://${WEB_SERVER_OUTER_SOCKET}/grafana/'
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_AUTH_BASIC_ENABLED: false
      GF_AUTH_DISABLE_LOGIN_FORM:  true
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: true
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: true
      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: true
      GF_AUTH_GENERIC_OAUTH_USE_TOKEN_INFO_ENDPOIT: false
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: '${KEYCLOAK_CLIENT_GRAFANA}'
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: 'full_name'
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: 'username'
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: 'email'
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE: '/run/secrets/keycloak_client_grafana_password'
      GF_AUTH_GENERIC_OAUTH_SCOPES: 'openid email profile offline_access roles'
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: 'https://${WEB_SERVER_OUTER_SOCKET}${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth'
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token'
      GF_AUTH_GENERIC_OAUTH_API_URL: 'http://keycloak:8080${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo'
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(resource_access.grafana.roles, 'grafana_admin') && 'Admin' || 'Viewer'"
      GF_LOG_LEVEL: '${METRIC_LOG_LEVEL:-info}'
    secrets:
      - keycloak_client_grafana_password
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_var:/var/lib/grafana'
    depends_on:
      grafana-loki:
        condition: service_healthy
      promtail:
        condition: service_healthy
      prometheus:
        condition: service_started

  grafana-loki:
    <<: *default
    image: grafana/loki:3.4.5
    expose:
      - '3100'
    volumes:
      - '${METRIC_OUTER_PATH}/metric.d/grafana/datasources/grafana-loki.yaml:/etc/loki/config.yaml:ro'
      - 'grafana_loki_data:/data/grafana_loki'
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:3100/ready | grep -q -w ready || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  promtail:
    <<: *default
    image: grafana/promtail:3.4.5
    command:
      - '-config.expand-env=true'
      - '-config.file=/etc/promtail/config.yaml'
    expose:
      - '9080'
    volumes:
      - 'promtail_data:/data/promtail'
      - '${METRIC_DOCKER_SOCKET}:/var/run/docker.sock'
      - '${METRIC_DOCKER_CONTAINERS_PATH}:/var/lib/docker/containers:ro'
      - '${METRIC_OUTER_PATH}/metric.d/promtail.yaml:/etc/promtail/config.yaml:ro'
    healthcheck:
          test: ["CMD-SHELL", "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/9080; exit $?;'"]
          start_period: 10s
          interval: 10s
          timeout: 5s
          retries: 3

  prometheus:
      <<: *default
      image: prom/prometheus:v3.5.0
      command:
        - '--web.external-url=https://${WEB_SERVER_OUTER_SOCKET}/prometheus/'
        - '--web.route-prefix=/prometheus/'
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - '9090:9090'
      volumes:
        - '${METRIC_OUTER_PATH}/metric.d/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
        - 'prometheus_data:/data/prometheus'

volumes:
  saltbox_metric_var: {}
  grafana_var: {}
  grafana_loki_data: {}
  promtail_data: {}
  prometheus_data: {}

secrets:
  keycloak_client_grafana_password:
    file: secrets/keycloak_client_grafana_password
