location /grafana/api/live/ {
    set $srv grafana;  # To be resolved
    proxy_pass http://$srv:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
}

location /grafana/ {
    set $srv grafana;  # To be resolved
    proxy_pass http://$srv:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Prefix /grafana;
}

location /prometheus/ {
    set $srv prometheus;  # To be resolved
    proxy_pass http://$srv:9090;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Prefix /prometheus;
}
