global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "saltbox-metric-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-metric-app:8004"]

  - job_name: "saltbox-core"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-core:8000"]

  - job_name: "saltbox-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-gateway:8001"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
