global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "saltbox-metric-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-metric-app:8004"]

  - job_name: "saltbox-core"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-core:8000"]

  - job_name: "saltbox-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["saltbox-gateway:8001"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        target_label: service

      - source_labels: [service, name]
        regex: '^$;/?(.+)'
        target_label: service
        replacement: '$1'

      - source_labels: [service]
        regex: 'saltbox-(.+)-1'
        target_label: service
        replacement: '$1'

      - source_labels: [service]
        regex: 'saltbox-(.+)'
        target_label: service
        replacement: '$1'

  - job_name: node
    static_configs:
      - targets: ['host.saltbox:9100']
