apiVersion: 1
groups:
    - orgId: 1
      name: docker-containers
      folder: Docker
      interval: 1m
      rules:
        - uid: bfmige7il0a2oa
          title: CPU Usage
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: rate(container_cpu_user_seconds_total{image!=""}[5m]) * 100
                instant: true
                interval: ""
                intervalFactor: 2
                intervalMs: 15000
                legendFormat: '{{service}}'
                maxDataPoints: 43200
                metric: cpu
                range: false
                refId: A
                step: 10
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 79
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: salt_box
          panelId: 25
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: salt_box
            __panelId__: "25"
            description: "Алерт срабатывает, когда нагрузка CPU в Docker-контейнере превышает 79% \nна протяжении 5 минут\n\nКонтейнер: {{ $labels.service }}\nТекущее значение: {{ $values.A.Value | printf \"%.1f\" }}%"
            summary: Высокая нагрузка на CPU в контейнере {{ $labels.service }}
          isPaused: false
          notification_settings:
            receiver: '[MAIN] Email Receiver'
    - orgId: 1
      name: docker-ram
      folder: Docker
      interval: 1m
      rules:
        - uid: cfmipxb86p91cc
          title: Memory Usage Docker
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 10800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: |-
                    container_memory_usage_bytes{name=~".+"}
                      / scalar(node_memory_MemTotal_bytes) * 100
                instant: true
                interval: ""
                intervalFactor: 2
                intervalMs: 15000
                legendFormat: '{{service}}'
                maxDataPoints: 43200
                metric: container_memory_usage_bytes
                range: false
                refId: A
                step: 10
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 60
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: salt_box
          panelId: 26
          noDataState: NoData
          execErrState: Error
          for: 2m
          keepFiringFor: 5m
          annotations:
            __dashboardUid__: salt_box
            __panelId__: "26"
            description: "Алерт срабатывает, когда потребление памяти Docker-контейнера превышает 60% \nот общего объёма RAM сервера"
            summary: Контейнер {{ $labels.service }} потребляет {{ $values.A.Value | printf "%.1f" }}% RAM сервера
          isPaused: false
          notification_settings:
            receiver: '[MAIN] Email Receiver'
    - orgId: 1
      name: host-ram
      folder: Docker
      interval: 1m
      rules:
        - uid: dfmito4p7bfuod
          title: CPU Basic
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: (1 - avg(rate(node_cpu_seconds_total{instance="host.saltbox:9100", job="node", mode="idle"}[$__rate_interval]))) * 100
                hide: false
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 95
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: salt_box
          panelId: 40
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: salt_box
            __panelId__: "40"
            description: |-
                Алерт срабатывает, когда суммарная нагрузка CPU превышает 95%
                на протяжении 5 минут.

                Текущая нагрузка: {{ $values.A.Value | printf "%.1f" }}%
            summary: 'Высокая нагрузка CPU на сервере: {{ $values.A.Value | printf "%.1f" }}%'
          isPaused: false
          notification_settings:
            receiver: '[MAIN] Email Receiver'
